/**
 * Sound for the three acts, shared between the header toggle and the stage.
 *
 * WHY THIS IS NOT SIMPLY "AUTOPLAY ON":
 *
 * Browsers will not start audio until the visitor has interacted with the page, and
 * scrolling does not count -- it takes a click, tap or key. So the PREFERENCE defaults
 * to on and is remembered, and the context is unlocked on the first real gesture,
 * wherever on the page it happens. The UI says "Enable sound" until then rather than
 * claiming to be on.
 *
 * THE TRAP THAT COST ME AN HOUR: when Chrome blocks a context, `resume()` returns a
 * promise that NEVER SETTLES. It does not reject -- it hangs. So `await ctx.resume()`
 * deadlocks its caller, and the gesture listeners downstream of it are never
 * installed. Nothing here awaits resume; the `statechange` event is the signal.
 *
 * WCAG 1.4.2: audio that starts on its own and runs past three seconds needs a stop
 * control, which is why the toggle lives in the header and not inside one act.
 *
 * Nothing is fetched. The rain is filtered noise and the bells are oscillators, so a
 * scroll can trigger a sound with no load and no decode wait. (The app's own rain.wav
 * is itself generated by tools/gen-rain.mjs, so synthesising here is the same idea.)
 */

export type Act = "none" | "water" | "eye" | "timer";

export interface SoundState {
  /** What the visitor wants. Persisted. */
  wanted: boolean;
  /** Whether the browser has actually let us start. */
  running: boolean;
}

type Ctor = typeof AudioContext;
const KEY = "fd:sound";

function readPref(): boolean {
  try {
    return window.localStorage.getItem(KEY) !== "off";
  } catch {
    return true; // private windows and blocked storage default to on
  }
}

function writePref(on: boolean) {
  try {
    window.localStorage.setItem(KEY, on ? "on" : "off");
  } catch {
    /* the preference just will not survive a reload */
  }
}

function createStageSound() {
  let ctx: AudioContext | null = null;
  let master: GainNode | null = null;
  let rainSrc: AudioBufferSourceNode | null = null;
  let rainGain: GainNode | null = null;
  let noise: AudioBuffer | null = null;
  let disarm: (() => void) | null = null;

  let wanted = true;
  let act: Act = "none";
  const listeners = new Set<(s: SoundState) => void>();

  const state = (): SoundState => ({ wanted, running: ctx?.state === "running" });
  const emit = () => listeners.forEach((fn) => fn(state()));

  /** Four seconds of pink-ish noise. A seam in noise is just more noise, so it loops. */
  function buildNoise(c: AudioContext) {
    const len = Math.floor(c.sampleRate * 4);
    const buf = c.createBuffer(1, len, c.sampleRate);
    const d = buf.getChannelData(0);
    let b0 = 0;
    let b1 = 0;
    let b2 = 0;
    for (let i = 0; i < len; i++) {
      const white = Math.random() * 2 - 1;
      b0 = 0.99765 * b0 + white * 0.099046;
      b1 = 0.963 * b1 + white * 0.2965164;
      b2 = 0.57 * b2 + white * 1.0526913;
      d[i] = (b0 + b1 + b2 + white * 0.1848) * 0.11;
    }
    return buf;
  }

  function startRain() {
    if (!ctx || !master || !noise || rainSrc) return;
    const hp = ctx.createBiquadFilter();
    hp.type = "highpass";
    hp.frequency.value = 190;
    const lp = ctx.createBiquadFilter();
    lp.type = "lowpass";
    lp.frequency.value = 1500;
    lp.Q.value = 0.6;

    rainGain = ctx.createGain();
    rainGain.gain.value = 0.0001;

    rainSrc = ctx.createBufferSource();
    rainSrc.buffer = noise;
    rainSrc.loop = true;
    rainSrc.connect(hp);
    hp.connect(lp);
    lp.connect(rainGain);
    rainGain.connect(master);
    rainSrc.start();
    // Fade in, never cut in.
    rainGain.gain.exponentialRampToValueAtTime(0.5, ctx.currentTime + 0.45);
  }

  function stopRain() {
    if (!ctx || !rainSrc || !rainGain) return;
    const src = rainSrc;
    const g = rainGain;
    rainSrc = null;
    rainGain = null;
    const now = ctx.currentTime;
    const end = now + 0.35;
    g.gain.cancelScheduledValues(now);
    g.gain.setValueAtTime(Math.max(g.gain.value, 0.0001), now);
    g.gain.exponentialRampToValueAtTime(0.0001, end);
    src.stop(end + 0.05);
  }

  /** Eye rest: a soft bowl, a fifth apart. Calm, because it means "stop looking". */
  function chime() {
    if (!ctx || !master) return;
    const t0 = ctx.currentTime + 0.02;
    [528, 792].forEach((f, i) => {
      const at = t0 + i * 0.07;
      const osc = ctx!.createOscillator();
      const g = ctx!.createGain();
      osc.type = "sine";
      osc.frequency.value = f;
      g.gain.setValueAtTime(0.0001, at);
      g.gain.linearRampToValueAtTime(i === 0 ? 0.1 : 0.06, at + 0.05);
      g.gain.exponentialRampToValueAtTime(0.0001, at + 1.9);
      osc.connect(g);
      g.connect(master!);
      osc.start(at);
      osc.stop(at + 2);
    });
  }

  /** Timer: three struck bells, 180ms apart. */
  function ding() {
    if (!ctx || !master || ctx.state !== "running") return;
    const t0 = ctx.currentTime + 0.02;
    for (let i = 0; i < 3; i++) {
      const at = t0 + i * 0.18;
      const osc = ctx.createOscillator();
      const g = ctx.createGain();
      osc.type = "sine";
      osc.frequency.value = 932;
      g.gain.setValueAtTime(0.0001, at);
      g.gain.exponentialRampToValueAtTime(0.16, at + 0.006);
      g.gain.exponentialRampToValueAtTime(0.0001, at + 0.26);
      osc.connect(g);
      g.connect(master);
      osc.start(at);
      osc.stop(at + 0.28);
    }
  }

  /**
   * Scroll drives this. Leaving an act stops its sound before the next one starts,
   * so two are never audible at once. The act is remembered even while muted, so it
   * can be applied the moment the browser lets us start.
   */
  function setAct(next: Act) {
    if (next === act) return;
    const from = act;
    act = next;
    if (!wanted || ctx?.state !== "running") return;
    if (from === "water") stopRain();
    if (next === "water") startRain();
    if (next === "eye") chime();
  }

  function attach() {
    if (ctx) return;
    const AC: Ctor | undefined =
      window.AudioContext ??
      (window as unknown as { webkitAudioContext?: Ctor }).webkitAudioContext;
    if (!AC) return;
    ctx = new AC();
    master = ctx.createGain();
    master.gain.value = 0.55;
    master.connect(ctx.destination);
    noise = buildNoise(ctx);

    ctx.addEventListener("statechange", () => {
      emit();
      if (ctx?.state === "running") {
        const current = act;
        act = "none";
        setAct(current);
        disarm?.();
        disarm = null;
      }
    });
  }

  /** Synchronous on purpose, so it is safe to call from inside a gesture handler. */
  function request(): boolean {
    attach();
    if (!ctx) return false;
    if (ctx.state === "suspended") void ctx.resume().catch(() => {});
    return ctx.state === "running";
  }

  /** The gesture the browser is waiting for, from anywhere on the page. */
  function armGesture() {
    const go = () => {
      if (!wanted) return;
      request();
      emit();
    };
    const off = () => {
      window.removeEventListener("pointerdown", go);
      window.removeEventListener("keydown", go);
      window.removeEventListener("touchstart", go);
    };
    window.addEventListener("pointerdown", go, { passive: true });
    window.addEventListener("keydown", go);
    window.addEventListener("touchstart", go, { passive: true });
    return off;
  }

  return {
    getState: state,

    subscribe(fn: (s: SoundState) => void) {
      listeners.add(fn);
      fn(state());
      return () => {
        listeners.delete(fn);
      };
    },

    /** Called once on mount: adopt the stored preference, then wait for a gesture. */
    init() {
      wanted = readPref();
      if (wanted) {
        request();
        if (ctx?.state !== "running") disarm = armGesture();
      }
      emit();
    },

    /** Open without flipping the preference, for the wanted-but-blocked case. */
    resume() {
      const ok = request();
      emit();
      return ok;
    },

    toggle() {
      wanted = !wanted;
      writePref(wanted);
      if (wanted) {
        request();
        if (ctx?.state !== "running" && !disarm) disarm = armGesture();
      } else {
        stopRain();
        disarm?.();
        disarm = null;
        void ctx?.suspend().catch(() => {});
      }
      emit();
      return state();
    },

    setAct,
    ding,

    silence() {
      stopRain();
      act = "none";
    },
  };
}

export type StageSound = ReturnType<typeof createStageSound>;

let shared: StageSound | null = null;

/** One instance, so the header toggle and the stage are the same sound. */
export function getStageSound(): StageSound {
  shared ??= createStageSound();
  return shared;
}
