import { chromium } from "playwright";
const OUT = "/private/tmp/claude-501/-Users-saurabhgrewal-Documents-Personal-macPetWeb/30447c15-57c7-4db8-a643-9b86800cf696/scratchpad";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 });
await p.goto(process.env.URL, { waitUntil: "networkidle" });
await p.waitForTimeout(700);
await p.screenshot({ path: `${OUT}/top.png` });
const m = await b.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
await m.goto(process.env.URL, { waitUntil: "networkidle" });
await m.waitForTimeout(700);
await m.screenshot({ path: `${OUT}/top-phone.png` });
await b.close();
console.log("ok");
